#!/bin/bash

# Create an array of algorithm names
algorithms=(
  "bruteForce"
  "greedyAlgorithms"
  "divideAndConquer"
  "dynamicProgramming"
  "backtracking"
  "recursion"
  "memoization"
  "branchAndBound"
  "twoPointersLeftRight"
  "twoPointersFastSlow"
  "binarySearch"
  "binarySearchOnAnswer"
  "slidingWindowFixedSize"
  "slidingWindowVariableSize"
  "bfs"
  "dfs"
  "dijkstra"
  "bellmanFord"
  "floydWarshall"
  "kruskal"
  "prim"
  "topologicalSort"
  "aStar"
  "treeTraversals"
  "bstOperations"
  "segmentTrees"
  "fenwickTrees"
  "hashTables"
  "hashSets"
  "quickSort"
  "mergeSort"
  "heapSort"
  "bubbleSort"
  "insertionSort"
  "selectionSort"
  "countingSort"
  "radixSort"
  "bucketSort"
  "linearSearch"
  "exponentialSearch"
  "interpolationSearch"
  "euclideanAlgorithm"
  "sieveOfEratosthenes"
  "fft"
  "modularArithmetic"
  "exponentiationBySquaring"
  "kmp"
  "rabinKarp"
  "zAlgorithm"
  "ahoCorasick"
  "trie"
  "convexHull"
  "lineIntersection"
  "closestPairOfPoints"
  "bitMasking"
  "bitwiseOperators"
  "monteCarlo"
  "lasVegas"
  "primeFactorization"
  "modularExponentiation"
  "chineseRemainderTheorem"
  "minimax"
  "alphaBetaPruning"
  "geneticAlgorithms"
  "simulatedAnnealing"
  "tabuSearch"
  "approximationAlgorithms"
  "huffmanCoding"
  "rle"
  "lzwCompression"
)

# Create a js file for each algorithm in the array
for algorithm in "${algorithms[@]}"; do
  touch "${algorithm}.js"
done

echo "All files have been created successfully!"
